### ISSUE TITLE
input/Buddha/lf.bmp

### ISSUE THREAD

**Issue by bhack** [shuozh/Spinning-Parallelogram-Operator#1]
Are there any missing files?

**Comment by shuozh** [comment]
The light field image can be downloaded from the 4D light field benchmark: http://hci-lightfield.iwr.uni-heidelberg.de/ . 

The (x,y) in 'lf.bmp' changes in the angular domain firstly and the spatial domain secondly.

**Comment by bhack** [comment]
Do you have already a script  to arrange the bmp from the multiview?
